// Generate TOS hash v3 test vectors
// Run: cd ~/tos/tck/hash && cargo run --release --bin gen_tos_hash_v3_vectors

use serde::Serialize;
use std::fs::File;
use std::io::Write;
use tos_hash::v3;

#[derive(Serialize)]
struct HashVector {
    name: String,
    description: String,
    input_hex: String,
    input_len: usize,
    expected_hash_hex: String,
}

#[derive(Serialize)]
struct HashV3VectorFile {
    algorithm: String,
    version: u32,
    description: String,
    source: String,
    test_vectors: Vec<HashVector>,
}

fn to_hex(bytes: &[u8]) -> String {
    hex::encode(bytes)
}

fn hash_v3(input: &[u8]) -> String {
    let mut scratchpad = v3::ScratchPad::default();
    let out = v3::tos_hash(input, &mut scratchpad).expect("v3 hash failed");
    to_hex(&out)
}

fn main() {
    let mut vectors = Vec::new();

    let zeros_112 = vec![0u8; 112];
    vectors.push(HashVector {
        name: "zeros_112_bytes".to_string(),
        description: "112-byte all-zero input".to_string(),
        input_hex: to_hex(&zeros_112),
        input_len: zeros_112.len(),
        expected_hash_hex: hash_v3(&zeros_112),
    });

    let mut first_one_112 = vec![0u8; 112];
    first_one_112[0] = 1;
    vectors.push(HashVector {
        name: "first_byte_one_rest_zero_112_bytes".to_string(),
        description: "112-byte input with byte[0]=1 and remaining bytes zero".to_string(),
        input_hex: to_hex(&first_one_112),
        input_len: first_one_112.len(),
        expected_hash_hex: hash_v3(&first_one_112),
    });

    let ascii = b"test input for tos hash v3".to_vec();
    vectors.push(HashVector {
        name: "ascii_phrase".to_string(),
        description: "ASCII input string 'test input for tos hash v3'".to_string(),
        input_hex: to_hex(&ascii),
        input_len: ascii.len(),
        expected_hash_hex: hash_v3(&ascii),
    });

    let output = HashV3VectorFile {
        algorithm: "TOS_HASH_V3".to_string(),
        version: 1,
        description: "TOS hash v3 test vectors generated by tos-hash Rust module".to_string(),
        source: "tos-hash::v3::tos_hash".to_string(),
        test_vectors: vectors,
    };

    let yaml = serde_yaml::to_string(&output).expect("Failed to serialize YAML");
    println!("{}", yaml);

    let output_path = "tos_hash_v3.yaml";
    let mut file = File::create(output_path).expect("Failed to create output file");
    file.write_all(yaml.as_bytes())
        .expect("Failed to write output file");
    eprintln!("Written to {}", output_path);
}
