description: RocksDB database operation test vectors for TOS/Avatar compatibility
version: '1.0'
note: Execute operations in order, then verify queries return expected results.
column_family_configs:
- name: accounts
  description: Account state storage
  key_format: account_id (u64 BE)
  value_format: Account struct (id + optional fields)
- name: nonces
  description: Account nonce versions
  key_format: account_id (u64 BE) + topoheight (u64 BE)
  value_format: VersionedNonce (previous_topo + nonce)
- name: balances
  description: Account balance versions
  key_format: account_id (u64 BE) + asset_hash (32 bytes) + topoheight (u64 BE)
  value_format: VersionedBalance (previous_topo + type + final + output)
- name: topoheight_to_hash
  description: Map topoheight to block hash
  key_format: topoheight (u64 BE)
  value_format: block_hash (32 bytes)
- name: hash_to_topoheight
  description: Map block hash to topoheight
  key_format: block_hash (32 bytes)
  value_format: topoheight (u64 BE)
account_operations:
- name: put_account_genesis
  description: Insert genesis account (id=0)
  operation: put
  column_family: accounts
  key_hex: '0000000000000000'
  value_hex: '000000000000000000000000'
  account_id: 0
  registered_at: null
  nonce_pointer: null
  multisig_pointer: null
  energy_pointer: null
- name: put_account_1
  description: Insert account 1 with registration
  operation: put
  column_family: accounts
  key_hex: '0000000000000001'
  value_hex: '00000000000000010100000000000000000100000000000000000000'
  account_id: 1
  registered_at: 0
  nonce_pointer: 0
  multisig_pointer: null
  energy_pointer: null
- name: put_account_42
  description: Insert account 42 with all fields
  operation: put
  column_family: accounts
  key_hex: 000000000000002a
  value_hex: 000000000000002a0100000000000000640100000000000000c801000000000000012c010000000000000190
  account_id: 42
  registered_at: 100
  nonce_pointer: 200
  multisig_pointer: 300
  energy_pointer: 400
nonce_operations:
- name: put_nonce_initial
  description: Initial nonce for account 1 at genesis
  operation: put
  column_family: nonces
  key_hex: '00000000000000010000000000000000'
  value_hex: '000000000000000000'
  account_id: 1
  topoheight: 0
  previous_topoheight: null
  nonce: 0
- name: put_nonce_after_txs
  description: Nonce after 5 transactions
  operation: put
  column_family: nonces
  key_hex: '00000000000000010000000000000064'
  value_hex: '0100000000000000000000000000000005'
  account_id: 1
  topoheight: 100
  previous_topoheight: 0
  nonce: 5
balance_operations:
- name: put_balance_genesis
  description: Genesis balance for account 1 (1000 TOS)
  operation: put
  column_family: balances
  key_hex: '000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000'
  value_hex: 0000000000174876e80000
  account_id: 1
  asset_hash_hex: '0000000000000000000000000000000000000000000000000000000000000000'
  topoheight: 0
  previous_topoheight: null
  balance_type: input
  final_balance: 100000000000
  output_balance: null
- name: put_balance_after_send
  description: Balance after sending 100 TOS
  operation: put
  column_family: balances
  key_hex: '000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000064'
  value_hex: 0100000000000000000200000014f46b04000100000002540be400
  account_id: 1
  asset_hash_hex: '0000000000000000000000000000000000000000000000000000000000000000'
  topoheight: 100
  previous_topoheight: 0
  balance_type: both
  final_balance: 90000000000
  output_balance: 10000000000
topoheight_operations:
- name: put_topo_genesis
  description: Map topoheight 0 to genesis block
  operation: put
  column_family: topoheight_to_hash
  key_hex: '0000000000000000'
  value_hex: '0000000000000000000000000000000000000000000000000000000000000001'
  topoheight: 0
  block_hash_hex: '0000000000000000000000000000000000000000000000000000000000000001'
query_vectors:
- name: query_account_exists
  description: Query existing account 42
  query_type: get
  column_family: accounts
  key_hex: 000000000000002a
  expected_found: true
  expected_value_hex: 000000000000002a0100000000000000640100000000000000c801000000000000012c010000000000000190
- name: query_account_not_exists
  description: Query non-existent account
  query_type: get
  column_family: accounts
  key_hex: 000000000000270f
  expected_found: false
  expected_value_hex: null
